#!/usr/bin/env python
import os
import sys

from src.app import CrowbarApp

print("Pythor nocks!")

CFG = {
    'basedir': os.path.dirname(os.path.abspath(__file__)) + "/",
    'app_name': 'Crowbar',
}

print("starting app ...")
app = CrowbarApp(CFG, sys.argv)
app.run()
print("app stopped.")
